name: develop
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: configure golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - name: checkout code
        uses: actions/checkout@v2